# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- azure-pipelines

jobs:
  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python27:
          python.version: '2.7'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
      displayName: 'Update pip'

    - script: |
        sudo apt-get update
        sudo apt-get install -y tcsh csh cmake
      displayName: "Install dependencies for testing"

    - script: |
        pip install pytest
        pytest --junitxml=junit/test-results.xml
      displayName: 'Test with pytest'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'
      

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        Python27:
          python.version: '2.7'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'

      - script: |
          pip install --upgrade pip
        displayName: 'Ensure pip is latest version'

      - script: |
          pip install --upgrade pytest
        displayName: 'Install test dependencies'
      # - powershell: |
      #     python install.py $(Pipeline.Workspace)\rez_install
      #   displayName: 'Install rez'

      - script: |
          pytest --junitxml=junit/test-results.xml
        displayName: 'Run pytest'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: '**/test-*.xml'
          testRunTitle: 'Publish test results for Python $(python.version)'
