name: installation
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/installation.yaml'
      - '!src/rez/utils/_version.py'
      - '!**.md'

jobs:
  main:
    name: ${{ matrix.os }} - ${{ matrix.python-version }} - ${{ matrix.method }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
            OS: "test"
          - macOS-latest
          - windows-2019]
        python-version:
          - '2.7'
          - '3.7'
        method:
          - 'install'
          - 'pip'
    env:
      OS: ${{ matrix.os }}
    

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        echo $OS
        echo {{ $OS }}