name: installation
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/installation.yaml'
      - '!src/rez/utils/_version.py'
      - '!**.md'

jobs:
  main:
    name: ${{ matrix.os }} - ${{ matrix.python-version }} - ${{ matrix.method }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macOS-latest
          - windows-2019]
        python-version:
          - '2.7'
          - '3.7'
        method:
          - 'install'
          - 'pip'
        include:
          - os: ubuntu-latest
          REZ_INSTALL_PATH: /opt/rez
          - os: macOS-latest
          REZ_INSTALL_PATH: /opt/rez
          - os: windows-2019]
          REZ_INSTALL_PATH: c:\ProgramData\rez

  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        echo REZ_INSTALL_PATH

#   - name: Install
#       run: |
#         $env:REZ_PATH=
#       if: matrix.os 0== 'windows-latest'